version: "3"

services:
  actions-runner:
    build:
      context: .
    image: ansible-images/actions-runner
    container_name: ansible-images-actions-runner
    environment:
      - RUNNER_TOKEN=${RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
