- name: Ensure variables are set
  assert:
    that:
      - controller_host is defined
      - controller_host|length > 0
      - controller_username is defined
      - controller_username|length > 0
      - controller_password is defined or controller_oauthtoken is defined
      - (controller_password|length > 0) or (controller_oauthtoken|length > 0)
    quiet: true
