resource_dir: /resources

# List of all asset types supported for downloading and creating.
supported_asset_types:
  - execution_environments
  - organizations
  - notification_templates
  - users
  - teams
  - credential_types
  - credentials
  - projects
  - inventory
  - inventory_sources
  - job_templates
  - workflow_job_templates
  - workflow_job_template_nodes
  - schedules

asset_types: "{{ supported_asset_types }}"

# A regex for each asset type for resources to ignore by name.
ignore_assets:
  execution_environments: ''
  notification_templates: ''
  organizations: ''
  users: ''
  teams: ''
  credential_types: ''
  credentials: ''
  projects: ''
  inventory: ''
  inventory_sources: ''
  job_templates: ''
  workflow_job_templates: ''
  schedules: ''
