- name: Create AWX resources.
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - common
  tasks:
  - name: Output AWX host
    debug: msg="Creating resources on {{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"

  - name: Check existence of resources directory
    stat:
      path: "{{ resource_dir }}"
    register: resources_dir_stat

  - name: Ensure resources directory exists
    assert:
      that: resources_dir_stat.stat.exists
      quiet: true

  - name: Request confirmation
    pause:
      prompt: |
        Please note that this operation may overwrite changes on the Production
        instance! Press return to continue. Press Ctrl+c and then "a" to abort.

  - name: Create resources
    include_role:
      name: create-resources
    loop: "{{ asset_types }}"
    loop_control:
      loop_var: asset_type
