name: awx-resources

on:
  push:
    branches: [ main ]
    paths:
      - 'awx-resources/Dockerfile'
      - 'awx-resources/playbooks'
  workflow_dispatch:
    inputs:
      ansible_image_version:
        description: 'Version of base Ansible image to use'
        default: '3.10'
        type: choice
        options:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'

env:
  REGISTRY: ghcr.io

jobs:
  bake:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_IMAGE_VERSION: ${{ inputs.ansible_image_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64,amd64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set python_version value
        id: ansible_image_version
        run: |
          ANSIBLE_IMAGE_VERSION=${{ inputs.ansible_image_version }}
          echo "::set-output name=value::${ANSIBLE_IMAGE_VERSION:-"3.10"}"

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          targets: awx-resources
        env:
          ANSIBLE_IMAGE_VERSION: ${{ steps.ansible_image_version.outputs.value }}
