name: awx

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  bake:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the Dockerfile
        run: cd awx && ./create-dockerfile.sh

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          targets: awx
