name: awx

on:
  workflow_dispatch:
    inputs:
      awx_version:
        description: 'Version of AWX to build'
        default: '22.0.0'
        type: choice
        options:
        - '19.4.0'
        - '22.6.0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: salsadigitalauorg/awx
  # Versions for which to use our custom dockerfile script.
  BUILD_CUSTOM_SCRIPT_VERSIONS: '["19.4.0"]'

jobs:
  bake:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the Dockerfile
        run: cd awx && ./create-dockerfile.sh
        if: ${{ contains(fromJSON(env.BUILD_CUSTOM_SCRIPT_VERSIONS), inputs.awx_version) }}

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          targets: awx
        if: ${{ contains(fromJSON(env.BUILD_CUSTOM_SCRIPT_VERSIONS), inputs.awx_version) }}

      - name: Checkout awx
        uses: actions/checkout@v2
        with:
          repository: ansible/awx
          path: ansible-awx
        if: ${{ !contains(fromJSON(env.BUILD_CUSTOM_SCRIPT_VERSIONS), inputs.awx_version) }}

      - name: Build using ansible
        working-directory: ansible-awx
        run: |
          ansible-playbook -v tools/ansible/build.yml \
            -e registry=${{ env.REGISTRY }} \
            -e registry_username=${{ github.actor }} \
            -e registry_password=${{ secrets.GITHUB_TOKEN }} \
            -e awx_image=${{ env.IMAGE_NAME }} \
            -e awx_version=${{ inputs.awx_version }}
        if: ${{ !contains(fromJSON(env.BUILD_CUSTOM_SCRIPT_VERSIONS), inputs.awx_version) }}

      - name: Tag & push
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ inputs.awx_version }} ghcr.io/${{ env.IMAGE_NAME }}:${{ inputs.awx_version }}
          docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ inputs.awx_version }}
        if: ${{ !contains(fromJSON(env.BUILD_CUSTOM_SCRIPT_VERSIONS), inputs.awx_version) }}
