name: python-crossbuild image

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/image-python-crossbuild.yml'
      - 'Dockerfile.python-crossbuild'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  bake-python-crossbuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - '3.8'
          - '3.9'
          - '3.10'
          # 3.11 is failing with ERROR: module 'sysconfig' has no attribute '_is_python_source_dir'
          # Follow https://github.com/benfogle/crossenv/issues/103 &
          # https://github.com/benfogle/crossenv/pull/104 for more.
          # - '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          targets: python-crossbuild
        env:
          PYTHON_VERSION: ${{ matrix.python_version }}
