name: ansible image

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.ansible'
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Version of Python to use'
        default: '3.10'
        type: choice
        options:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'

env:
  REGISTRY: ghcr.io

jobs:
  bake-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64,amd64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set python_version value
        id: python_version
        run: |
          PYTHON_VERSION=${{ inputs.python_version }}
          echo "::set-output name=value::${PYTHON_VERSION:-"3.10"}"

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          targets: ansible
        env:
          PYTHON_VERSION: ${{ steps.python_version.outputs.value }}
