name: ansible-runner image

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.ansible-runner'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  bake-ansible-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64,amd64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          targets: ansible-runner
